version: '3.1'

services:

  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: on-failure
    network_mode: "host"
    ports:
      - 8080:8080
